spring:
  application:
    name: service-consumer

server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: service-consumer8082
    prefer-ip-address: true

info:
  app.name: service_consumer
  company: kither