spring:
  application:
    name: service-consumer2

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    instance-id: service-consumer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/